### ISSUE TITLE
Config parsing : accents in measure names 

### ISSUE THREAD

**Issue by vviers** [transform-data/metricflow#356] opened 2022-11-23 10:30 UTC
Hi it's me again 👋🏼 🇫🇷 

**Describe the bug**

In PostgreSQL (the DWH i'm using), column names can have accents (e.g. `formé`)

However, if I try and configure a `data_source.measure.name` with a `é` I get the following error :

<img width="1326" alt="Screenshot 2022-11-23 at 10 44 26" src="https://user-images.githubusercontent.com/30295971/203522446-96bddb06-cc7a-4c0d-b489-e91f070ef707.png">

**Steps To Reproduce**

```yaml
measures:
    - name: formé
      description: Indique si l'aidant a été formé. 
      agg: sum_boolean
      create_metric: true
      create_metric_display_name: "Nombre d'aidants formés"
```

`mf validate-config`

**Expected behavior**
I'd expect validate-config to pass.

**Environment (please complete the following information):**

```sh
> $ mf version
0.130.1
```

**Comment by vviers** [comment] 2022-11-23 10:30
FWIW, this "hack" works : 

```yaml
  measures:
    - name: forme
      description: Indique si l'aidant a été formé. 
      expr: formé # This is a hack: MetricFlow won't let you use accents in names
      agg: sum_boolean
      create_metric: true
      create_metric_display_name: "Nombre d'aidants formés"
```

**Comment by vvlu603** [comment] 2022-11-23 20:34
Hi Vincent! 

Glad to see that you found a workaround -- this is (technically) by design, where the "expr" parameter specifically allows you to specify the underlying column name while the "name" parameter is used by the MetricFlow framework (like an alias). 
More documentation is available here: https://docs.transform.co/docs/metricflow/reference/data-sources/measures 

I'll close this issue for now, but will file this internally with our engineers. 

Thank you! And as always, we are more than happy to hear your feedback, bugs, comments, feature requests, and more! 

-Vivian

**Closed by vvlu603** 2022-11-23 20:34 UTC
Labels: bug, triage
